# Generated by Django 3.0.7 on 2023-11-19 18:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('invoice', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.IntegerField(blank=True, max_length=200, null=True)),
                ('quantity', models.IntegerField(blank=True, max_length=200, null=True)),
                ('subtotal', models.IntegerField(blank=True, max_length=200, null=True)),
                ('tax', models.IntegerField(blank=True, max_length=200, null=True)),
                ('grand_total', models.IntegerField(blank=True, max_length=200, null=True)),
                ('discount', models.IntegerField(blank=True, max_length=200, null=True)),
                ('payment_method', models.CharField(choices=[('Esewa', 'Esewa'), ('Banktransfer', 'Banktransfer'), ('COD', 'COD')], default='COD', max_length=100)),
                ('date', models.DateField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
