# Generated by Django 3.0.7 on 2023-11-22 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printbill', '0003_auto_20231121_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='delivey_fee',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
