# Generated by Django 3.0.7 on 2023-11-26 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printbill', '0004_auto_20231122_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
